### ISSUE TITLE
Flowbox example doesn't show colors

### ISSUE THREAD

**Issue by marekjedrzejewski** [sebp/PyGObject-Tutorial#117]
override_background_color is deprecated, and doesn't work.
Documentation says:
Deprecated since version 3.16: This function is not useful in the context of CSS-based rendering. If you wish to change the way a widget renders its background you should use a custom CSS style, through an application-specific Gtk.StyleProvider and a CSS style class. You can also override the default drawing of a widget through the Gtk.Widget ::draw signal, and use Cairo to draw a specific color, regardless of the CSS style.

I don't think things mentioned in documentation are the best way to do it in this case, so I used Gtk.ColorButton there, but it's probably not the same thing as intended, cause it opens color change window on click. What would be the best way to do it?

**Comment by sebp** [comment]
This fixed with commit 196e804660e43934632d60337350bb9fd1224102
