### ISSUE TITLE
How can create Translated tutorial ?

### ISSUE THREAD

**Issue by sebuls** [sebp/PyGObject-Tutorial#131]
I read 
https://python-gtk-3-tutorial.readthedocs.io/en/latest/
and I guess
https://python-gtk-3-tutorial.readthedocs.io/ko/latest/
shows Korean translation of the tutorial.
But not.

How can make Korean translation and into the ko directory ?

**Comment by sebp** [comment]
Currently, the tutorial has only been translated to Brazilian Portuguese. Translations are handled by gettext and requires providing .po files for each language as described [here](http://www.sphinx-doc.org/en/master/intl.html#translating). If you want to add Korean translation, I'd be happy to add it, please create a separate pull request for it.
