### ISSUE TITLE
About http://live.gnome.org/PyGObject

### ISSUE THREAD

**Issue by sebuls** [sebp/PyGObject-Tutorial#132]
Hello.

https://github.com/sebp/PyGObject-Tutorial
says
Tutorial for using GTK+ 3 in Python http://live.gnome.org/PyGObject
But, http://live.gnome.org/PyGObject redirected to
https://wiki.gnome.org/action/show/Projects/PyGObject?action=show&redirect=PyGObject
and that page says
https://pygobject.readthedocs.io

I'm confused.

**Comment by sebp** [comment]
Thanks, I updated the URL.
