### ISSUE TITLE
Cannot build Pygobject from source

### ISSUE THREAD

**Issue by anshulvj** [sebp/PyGObject-Tutorial#133]
I'm trying to build Pygobject on Ubuntu 64-bit 16.04. I followed instructions give here https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html#installing-from-source and I believe that the documentation needs more details:

Some points of confusion for me were:
1. The Pre-built packages section does not have any details on how to install `pygobject`. If possible can those be added?
2. Installing from source section refers to [1](https://download.gnome.org/teams/releng/) but does not specify which version to download. So I downloaded latest version. Then the instructions say 

> Once you have installed JHBuild successfully, download the latest configuration from [1]. Copy files with the suffix .modules to JHBuild’s module directory and the file sample-tarball.jhbuildrc to ~/.jhbuildrc.

But in the downloaded folder from [1] I could not find any `.modules` files. What exactly needs to be done here is not clear to me.

3. I followed instructions given at https://developer.gnome.org/jhbuild/unstable/getting-started.html.en and they were successful. The `jhbuild sanitycheck` was also successful.

4. After I run `jhbuild build pygobject` I get a whole bunch of errors. For e.g.:

```
`Checking if "C_IN in public headers (no arpa/nameser_compat.h needed)" 
compiles: NO
Checking if "arpa/nameser_compat.h needed for C_IN" compiles: NO

gio/meson.build:35:6: ERROR:  Problem encountered: Could not find 
required includes for ARPA C_IN

A full log can be found at 
/home/anshulvj/.cache/jhbuild/build/glib/meson-logs/meson-log.txt
*** Error during phase configure of glib: ########## Error running 
meson --prefix /home/anshulvj/jhbuild/install --libdir lib - 
Dlibmount=false --buildtype=debugoptimized -Dgtk_doc=false 
/home/anshulvj/jhbuild/checkout/glib *** [6/10]

[1] Rerun phase configure
[2] Ignore error and continue to build
[3] Give up on module
[4] Start shell
[5] Reload configuration
[6] Go to phase "wipe directory and start over"
choice: `
```
Doesn't matter what I choose, it either ends the build or gives errors like the following, if I choose [2]:

```
*** Building glib *** [6/10]
ninja  
ninja: error: loading 'build.ninja': No such file or directory
*** Error during phase build of glib: ########## Error running ninja   
*** [6/10]
.
.
.

```
and then
```
configure: error: Package requirements (glib-2.0 >= 2.57.1) were not met:

Requested 'glib-2.0 >= 2.57.1' but version of GLib is 2.48.2

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_CFLAGS
and GLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
*** Error during phase configure of gobject-introspection: ########## Error running /home/anshulvj/jhbuild/checkout/gobject-introspection/autogen.sh --prefix /home/anshulvj/jhbuild/install --disable-Werror --with-python=python3 --disable-static --disable-gtk-doc  *** [9/10]
```
Which is weird because I cannot find anything related to installing glib2.57 or greater online. (https://github.com/GNOME/glib)

The documentation at https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html does not deal with these errors and I'm completely lost. I googled a lot but did not find anyone who was facing the same issue. If this does not work I'm going to give up on Python3+GTK3+.

Any help/pointers are appreciated.

**Comment by sebp** [comment]
Most modern distributions have PyGObject installed already. If you still want to built from source to have the latest version, I'd suggest you ask on the [python-hackers-list](https://mail.gnome.org/mailman/listinfo/python-hackers-list).
