### ISSUE TITLE
you need to find some other way for people to install this, cause some of us can't install it the way you say.

### ISSUE THREAD

**Issue by nickgrier07** [sebp/PyGObject-Tutorial#144]
seriously, I can't connect to git from my terminal, so I need some other way of installing this.

IT should be a simple "sudo apt get install", so make it that way.

**Comment by gianmt** [comment]
I'm sure Sebp won't mind if you create a package and submit it

**Comment by sebp** [comment]
For general PyGObject and GTK+ questions, please ask on [python-hackers-list](https://mail.gnome.org/mailman/listinfo/python-hackers-list), [gtk-app-devel-list](https://mail.gnome.org/mailman/listinfo/gtk-app-devel-list) or http://stackoverflow.com/
