### ISSUE TITLE
Please provide a release / offline version

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [sebp/PyGObject-Tutorial#152]
I often work offline.

So I tried to "build" your pygobject-tutorial doc files by myself. Did not worked.

It would be nice if you could provide a release that I could use offline. Or provide detailed how-to-build instruction.

**Comment by PQYPLZXHGF** [comment]
What errors did you get?

Hint: Install the requirements.txt and then run the Makefile 👍

**Comment by sebp** [comment]
See https://readthedocs.org/projects/python-gtk-3-tutorial/downloads/
