### ISSUE TITLE
Update JHBuild manual link

### ISSUE THREAD

**Issue by ycanales** [sebp/PyGObject-Tutorial#153]
In section [1.3. Installing From Source](https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html#installing-from-source) the [currently linked page](https://developer.gnome.org/jhbuild/unstable/) instructs to clone from `git clone git://git.gnome.org/jhbuild`, which no longer exists. [This page](https://wiki.gnome.org/Projects/Jhbuild/Introduction) instead gives the correct instruction to install from `git clone https://gitlab.gnome.org/GNOME/jhbuild.git`

**Comment by sebp** [comment]
Thanks for noting this issue. Since the linked document directly comes from upstream, I believe the best thing would be if you could file a bug at https://gitlab.gnome.org/GNOME/jhbuild to let them now that their reference manual needs to be updated.
