### ISSUE TITLE
Use a translation platform

### ISSUE THREAD

**Issue by rffontenelle** [sebp/PyGObject-Tutorial#160]
A few days ago I found this amazing tutorial, and notice it is translated to Brazilian Portuguese (loved it, since I'm Brazilian). Reading another issue I learned that translations were out-of-date, so they had to be removed -- totally understandable.

**Rationale:** Although dealing with Pull Requests creation and Git/GitHub stuff is not skyrocket complexity, not all translators want or know how to deal with it. When the project's translation process is more difficult, translator may lose interest to contribute to it. Or maybe the translator is not notified of the changes, so he/she doesn't know that things have to be updated, resulting in translation staying out-of-date.

**Suggestion:** setup translation in a translation platform to make it easier for the translators to contribute, and to have a central translation point where translators may find your project and contribute (personally, I'd contributed before if I knew). For example, [Weblate allows zero cost hosting for free projects](https://weblate.org/hosting/) and it reaches many translators. [Damned Lies](https://l10n.gnome.org/), used by [GNOME Translation Project](https://wiki.gnome.org/TranslationProject/), would be perfect to reach GNOME translation teams, although I've never seen sphinx-based documentation projects in there -- not sure it supports.

**Comment by maujin111** [comment]
I would glad to translate it into Spanish

**Comment by sebp** [comment]
Translations are now available on Damned Lies: 
https://l10n.gnome.org/module/pygobject-tutorial/

You would need to submit a merge request here on Github to push the 
translations to readthedocs.

**Comment by rffontenelle** [comment]
Awesome. So, now the translators have to file a Pull Request changing `translations/po/<lang>.po` where `<lang>` is the language code, e.g., `pt_BR`. I guess this could be closed?

**Comment by sebp** [comment]
Yes that correct. In addition, you would need to run `make split-po` from the translations directory to convert the single PO file into multiple PO files used by sphinx. There might still be some issue, so please let me know if you encounter any issues.

**Comment by rffontenelle** [comment]
@sebp I see 2 approaches for contributing with translations:

1. The translator provides only the single PO file and then a GitHub Actions workflow (which I creating for test proposes) would automatically split them, run a build test, commit and push the split files. Such workflow could also build documentation on open and update a PR. This would make it easier for the translator to contribute.

2. The translator provides both single file and split PO files, which would probably encourage building to test the translation. It would also mean more work for the translator to have to install tools to split the PO file.

Personally I prefer option 1, but if you prefer option 2, it would require me to update instructions in #167

**Comment by sebp** [comment]
I think 1. would a good approach, as this could also perform additional checks on whether  all documents can be build. If there's an issue, the PR would be marked as invalid automatically. This would require adding `translations/locale` to .gitignore to avoid local files being committed.

Nevertheless, I believe giving instructions on how to build everything locally is useful for debugging if a PR is rejected.

**Comment by maujin111** [comment]
In spanish traslation are many languajes codes, Wich one should i use? es_ES? es_MX? es_EC? I'm from Ecuador. Should i use es_ES for general spanish or es_MX for general latin american spanish?

**Comment by sebp** [comment]
The languages supported by Sphinx are listed at https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language

**Comment by maujin111** [comment]
ok, got it, spanish tranlation on the way

**Comment by sebp** [comment]
I added a [tox](tox.readthedocs.io/) configuration now. If you install tox (`pip install tox`) and just run `tox` from the root of this repository, it will generate individual .po files and build everything for all languages specified in `LINGUAS`. There's also a GitHub action that does the same when submitting a pull request. I still need to check if generation of individual PO files can also be done when deploying to readthedocs.org.

**Comment by rffontenelle** [comment]
I notice tox's `-e` flag allows to choose specific environment, allowing `ALL`for all of them. Currently there is only the environment `sphinx`. How about adding some overhead to each language? Would be awesome if there could be a environment for a language filled via command-line, but not sure that is possible with tox.

**Comment by sebp** [comment]
You could define one environment for each language in the tox.ini, but this would require a lot of duplication. Maybe there's a way to inject an environment variable that, when set, determines that only the specified language is built.

**Comment by rffontenelle** [comment]
Well, issue is solved, so closing. Thanks for implementing it!
