### ISSUE TITLE
Remove plus sign from GTK

### ISSUE THREAD

**Issue by rffontenelle** [sebp/PyGObject-Tutorial#166]
The plus sign (+) was removed from GTK name in GTK Hackfest 2019 (See [issue GNOME/gtk#1439](https://gitlab.gnome.org/GNOME/gtk/issues/1439), [hackfest report which mentioned the removal](https://blog.gtk.org/2019/02/08/report-from-the-gtk-hackfest-in-brussels/), [removal announce](https://mail.gnome.org/archives/gtk-devel-list/2019-February/msg00000.html)). The whole code, documentation, website, etc. was changed to reflect this change. Would be nice if it was applied in here too.

**Comment by sebp** [comment]
Thanks for mentioning this change. I'm a little bit confused though. The announcement mentions that the documentation has been updated, yet https://developer.gnome.org/gtk3/stable/ does read GTK+.

**Comment by rffontenelle** [comment]
This plus sign removal did not land before the stable version (3.x) e work has been done in GTK4 for sometime now. But references to GTK+ were removed from a lot of places, like [GTK's website](https://www.gtk.org/) and [forum posts and category name](https://discourse.gnome.org/tag/gtk).
