### ISSUE TITLE
WARNING: html_static_path entry '_static' does not exist

### ISSUE THREAD

**Issue by rffontenelle** [sebp/PyGObject-Tutorial#169]
When building the documentation using `make html`, this warning is displayed.  It would be nice to have this solved, so that automatizing the build with Sphinx' `-W` flag would allow to easily spot syntax errors like e.g. `:class:` wrongly written in translation file.

Environment: Arch Linux, [sphinx](https://www.archlinux.org/packages/community/any/python-sphinx/) 3.0.1

**Comment by sebp** [comment]
Is adding a `_static` with a `.gitkeep` file inside sufficient then?

**Comment by rffontenelle** [comment]
If no static file is used nor required for these docs, then simply commenting the [line 133 in source/conf.py](https://github.com/sebp/PyGObject-Tutorial/blob/master/source/conf.py#L133) is enough. Is that the case?
