### ISSUE TITLE
Installation instruction.

### ISSUE THREAD

**Issue by antoniocaruso** [sebp/PyGObject-Tutorial#170]
Dear GTK developers.

The tutorial is very good, but is useless, really. I tried to install gtk to work with python3 on MacOS (Catalina), I tried with brew, no works, I tried with pip3, no works. 
So please, a tutorial is an interesting stuff, of course. But have you ever thinked that NOBODY use Gtk (not in a linux os) because the lack of proper documentation on the installation phase on different platforms? 
p.s. I'm a developer, but I don't want to spend two hours to just try a library with python and I don't want to compile from scratch like if I have to build a distribution.
Moreover, I teach python in a university class, and I really like to use some gui that is more advanced of tkinter. I spent two minutes to open a window with QT, and I'm not still able to do it with GTK. Because developers, after all the work spent in writing this good tutorial do not realize how IMPOSSIBLE is to install your library under Windows/MacOs.

**Comment by sebp** [comment]
I can understand your frustration, but please note that I'm not a pygobject developer, nor do I have access to a non-Linux OS. However, I do welcome contributions describing the steps required to setup pygobject on other platforms. For any issue related to installing pygobject, please contact the developers directly at https://gitlab.gnome.org/GNOME/pygobject/-/issues
