### ISSUE TITLE
MessageDialog documentation is obsolete as and with errors

### ISSUE THREAD

**Issue by fredcox** [sebp/PyGObject-Tutorial#173]
Hi,

I lost one day try to make one Gtk.MessageDialog to show in my app. Yes, I only display a info feedback on app. 

So, all examples in [https://python-gtk-3-tutorial.readthedocs.io/en/latest/dialogs.html#messagedialog](https://python-gtk-3-tutorial.readthedocs.io/en/latest/dialogs.html#messagedialog)  is obsolete and totally incompatible with latest python gtk version.

**Comment by gianmt** [comment]
The examples are not obsolete or incompatible with the latest version, you are probably seeing some deprecation warnings for positional arguments
