### ISSUE TITLE
Explain how to add debug output (preferred way)

### ISSUE THREAD

**Issue by bittner** [sebp/PyGObject-Tutorial#180]
IIUC, GTK+ applications should use [gedit-debug](https://developer.gnome.org/gedit/stable/gedit-gedit-debug.html) for debug output. There are additional benefits to using those functions, as explained in the [Running and debugging GTK+ Applications](https://developer.gnome.org/gtk3/stable/gtk-running.html) section in the GTK+ docs.

Can anyone confirm this is true? Are there any tutorials that prove that point, so that we can go about adding that as a recommendation to this tutorial?

**Comment by sebp** [comment]
gedit-debug obviously is specific to gedit, not any GTK+ application. Only the `GTK_DEBUG` options can be used for any type of GTK+ application.
