### ISSUE TITLE
[Tutorial improvement] Please consider adding a subsection to install from source WITHOUT jhbuilder

### ISSUE THREAD

**Issue by rubyFeedback** [sebp/PyGObject-Tutorial#182]
Right now the docs mention jhbuilder:

https://python-gtk-3-tutorial.readthedocs.io/en/latest/install.html#installing-from-source

I don't want to use jhbuilder though. I love straight URLs to tarballs or git clone is also
fine. I hate non-transparent tools (I am fine IF they were transparent but IMO these
tools are almost always designed to keep the user dumb).

I can track dependencies on my own too; I think some others may prefer this as well,
so can for these guys a subsection be added that shows where to download the
python bindings and then how to run it PROVIDED THEY ALREADY HAVE ALL THE
DEPENDENCIES matched, or know how to get these dependencies on their own?

Right now this is simply missing. It is assumed that everyone is missing the
dependencies. I actually have all dependencies as-is, just lack the knowledge
how to get it to work with python (I know gtk somewhat via the ruby bindings).

**Comment by sebp** [comment]
This is definitely something that could be useful to advanced users. However, the tutorial is more aimed at beginners that are not familiar with the PyGObject and all its dependencies. Therefore, using an automated tool that installs all dependencies is preferred. If you are certain that you have all the dependencies, you can have a look at the [PyGObject development guide](https://pygobject.readthedocs.io/en/latest/devguide/index.html).
