### ISSUE TITLE
.pot translation file outdated

### ISSUE THREAD

**Issue by haaninjo** [sebp/PyGObject-Tutorial#194]
If I understand it correctly, the translation system att https://l10n.gnome.org uses https://github.com/sebp/PyGObject-Tutorial/blob/master/translations/PythonGTK3Tutorial.pot to offer translation files and show translation statistics.

However, that pot file has not been updated since 2020-04-18, so there are new strings that aren't offered for translation on l10n.gnome.org.

**Comment by sebp** [comment]
Thanks for letting me know. The POT has been updated.

**Comment by haaninjo** [comment]
Perfect! Works as expected, l10n.gnome.org is now up to date.
