### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by robertoalvesneto** [sebp/PyGObject-Tutorial#207]
I noticed a piece that had not been translated into Portuguese, so I decided to try to correct it:
![image](https://user-images.githubusercontent.com/56491810/148903417-1d2f4ba5-fc3e-436c-a49c-3396e9b26b98.png)

I have cloned, run and watched the project successfully. But the text has been translated and doesn't seem to show any error with sphinx marked.

I don't know what the problem would be.

The path of code problem is `/translations/po/pt_BR.po` on line `1861`

**Comment by rffontenelle** [comment]
@robertoalvesneto Thanks for the feedback and sorry for taking long to reply. I didn't see this until now. It happens I translated long time ago this documentation but didn't update until now. I'll be opening a PR to fix this and other untranslated strings.
