### ISSUE TITLE
Relicensing for combining with PyGObject

### ISSUE THREAD

**Issue by danyeaw** [sebp/PyGObject-Tutorial#222]
There is a project to centralize the PyGObject documentation which is underway: https://gitlab.gnome.org/GNOME/pygobject/-/issues/609.

One thing that would be nice would be to combine the [PyGObject Guide](https://gitlab.gnome.org/rafaelmardojai/pygobject-guide) which was derived from this project. Since it was derived from this project, it is licensed under the GFDL, but PyGObject, including the docs, is licensed under the LGPL.

How would you feel if we relicensed or dual licensed this project so that we could bring it back as part of a more central set of documentation?

## Agreed to License Change (48/62 or 77%)

1. @cjmayo - Yes
1. @sebp - Yes
1. @rffontenelle - Yes
1. @gianmt - Yes
1. @tshepang - Yes
1. @TingPing - Yes
1. @takeshi-aihana - Yes
1. @paretje - Yes
1. @lazka - Yes
1. @haaninjo - Yes
1. @mozbugbox - Yes
1. @abcleanonme - Yes
1. @TarasKuzyo - Yes
1. @mcrapet - Yes
1. @kam193 - Yes
1. @DevJac - Yes
1. @cydanil - Yes
1. @sam-m888 - Yes
1. @samdroid-apps - Yes
1. @shivdhar - Yes
1. @sharkwouter - Yes
1. @dispread - Yes
1. @ltsdw - Yes
1. @oddstr13 - Yes
1. @rst0git - Yes
1. @sullenel - Yes
1. @AlexanderStein - Yes
1. @ajphukan - Yes
1. @cas-- - Yes
1. @csicar - Yes
1. @giove91 - Yes
1. @k4rtik - Yes
1. @kamathln - Yes
1. @LunarEclipse363 - Yes
1. @mgedmin - Yes
1. @mark-summerfield - Yes
1. @MatheusNtg - Yes
1. @nicobatty - Yes
1. @NotAFile - Yes
1. @pwaring - Yes
1. @neynt - Yes
1. @anarcat - Yes 
1. @wolfv - Yes
1. @sebuls - Yes
1. @osamuaoki - Yes
1. @danyeaw - Yes
1. @danielquinn  - Yes (via email)
1. @liberforce - Ye (via email)

**Comment by rffontenelle** [comment]
Not mine, but thanks for the compliment 😀. @rafaelmardojai, maybe?

**Comment by sebp** [comment]
@danyeaw I'm open to re-licensing. Currently, there have been 70+ contributors. I'd assume you would need to reach out to everyone to get their approval for re-licensing too.

**Comment by danyeaw** [comment]
Whoops, thanks for the correction @rffontenelle, wrong Rafael, my fault :smile:

**Comment by danyeaw** [comment]
Hi @cjmayo, @rffontenelle, @dharmatech, @gianmt, @tshepang, @TingPing, @takeshi-aihana, @paretje, @hadware,  @lazka, @nazgul77, @haaninjo, @mozbugbox, @Xoristzatziki, @abcleanonme, @TarasKuzyo, @mcrapet, @kam193, @DevJac, @cydanil, @sam-m888, @samdroid-apps, @shivdhar, @Soulou, @timgates42, @SunyataZero, @vaurelios, @wolfv, @sharkwouter, @anarcat, @dispread, @hcpl, @ltsdw, @oddstr13, @rpunkfu, @rst0git, @sullenel, @smileboywtu, @thorsummoner, @tomazcunha, @sebuls, @AlexanderStein, @and471, @ajphukan, @cas--, @csicar, @chang-zhao, @danielquinn, @fdg-org, @giove91, @neynt, @k4rtik, @kamathln, @xapantu, @liberforce, @LunarEclipse363, @mgedmin, @mark-summerfield, @MatheusNtg, @nicobatty, @NotAFile, @osamuaoki, and @pwaring.

Thanks for your previous contributions to the PyGObject-Tutorial. We would like to relicense the project to LGPL, so we can merge the derivative [PyGObject Guide](https://gitlab.gnome.org/rafaelmardojai/pygobject-guide) with the main PyGObject docs. Could I please get your permission to relicense your contribution from the GFDL to LGPL? Thanks!

**Comment by danyeaw** [comment]
Hi @neynt, @k4rtik, @kamathln, @xapantu, @liberforce, @LunarEclipse363, @mgedmin, @mark-summerfield, @MatheusNtg, @nicobatty, @NotAFile, @osamuaoki, and @pwaring.

Thanks for your previous contributions to the PyGObject-Tutorial. We would like to relicense the project to LGPL, so we can merge the derivative [PyGObject Guide](https://gitlab.gnome.org/rafaelmardojai/pygobject-guide) with the main PyGObject docs. Could I please get your permission to relicense your contribution from the GFDL to LGPL? Thanks!

**Comment by rffontenelle** [comment]
Granted

**Comment by haaninjo** [comment]
I'm fine with relicensing.

**Comment by shivdhar** [comment]
I'm okay, and additionally appreciate the way this is being carried out :)

**Comment by ltsdw** [comment]
Granted.

**Comment by giove91** [comment]
Sure!

**Comment by abcleanonme** [comment]
Absolutely!

**Comment by cydanil** [comment]
No problems! Thank you for taking the time to ensure that the project
continues, it's much appreciated :)

**Comment by k4rtik** [comment]
> Could I please get your permission to relicense your contribution from the GFDL to LGPL?

Yes, please.

**Comment by LunarEclipse363** [comment]
I'm fine with relicensing 👍

**Comment by dispread** [comment]
Sure

**Comment by hadware** [comment]
Sure

**Comment by kam193** [comment]
Yes, no problem for me.

**Comment by csicar** [comment]
Sure! Granted

**Comment by csicar** [comment]
Sure! Granted

**Comment by TingPing** [comment]
I approve re-licensing my contributions.

**Comment by gianmt** [comment]
I'm fine with relicensing

**Comment by TarasKuzyo** [comment]
Sure

нд, 5 трав. 2024 р. о 00:53 Gian Mario Tagliaretti ***@***.***>
пише:

**Comment by oddstr13** [comment]
LGPL is fine with me

**Comment by sullenel** [comment]
Sure

**Comment by lazka** [comment]
Sure

**Comment by sharkwouter** [comment]
Works for me

**Comment by MatheusNtg** [comment]
Sure, I approve it! Thanks!

Em sáb., 4 de mai. de 2024 15:43, Dan Yeaw ***@***.***>
escreveu:

**Comment by samdroid-apps** [comment]
Sounds good to me

**Comment by kamathln** [comment]
I agree to relicense my contributions under LGPL

**Comment by nicobatty** [comment]
I agree to relicense my contributions under LGPL

**Comment by mcrapet** [comment]
Granted.

**Comment by rst0git** [comment]
Sounds good to me

**Comment by sam-m888** [comment]
Yes, I agree to relicense my contributions under LGPL. Thank you.

**Comment by mark-summerfield** [comment]
> Hi @neynt, @k4rtik, @kamathln, @xapantu, @liberforce, @LunarEclipse363, @mgedmin, @mark-summerfield, @MatheusNtg, @nicobatty, @NotAFile, @osamuaoki, and @pwaring.
> 
> Thanks for your previous contributions to the PyGObject-Tutorial. We would like to relicense the project to LGPL, so we can merge the derivative [PyGObject Guide](https://gitlab.gnome.org/rafaelmardojai/pygobject-guide) with the main PyGObject docs. Could I please get your permission to relicense your contribution from the GFDL to LGPL? Thanks!

You are welcome to relicense whatever I've contributed.

**Comment by AlexanderStein** [comment]
Granted

**Comment by takeshi-aihana** [comment]
Thanks for the info. I'm Okay with doing re-licensing.

--
（TAKESHI）

**Comment by cas--** [comment]
Sure that's fine

**Comment by pwaring** [comment]
I don't even remember contributing, but I'm happy for whatever commits I made to be relicensed as LGPL.

**Comment by ajphukan** [comment]
Granted

**Comment by mozbugbox** [comment]
Granted
Thanks for your work.

    On Thursday, 9 May 2024 at 02:39:56 am GMT+8, Ankur Jyoti Phukan ***@***.***> wrote:  
 
 


Granted

**Comment by paretje** [comment]
Granted

**Comment by danyeaw** [comment]
## No Response Yet

1. @anarcat 
1. @hcpl 
1. @rpunkfu 
1. @and471 
1. @xapantu 
1. @liberforce 
1. @osamuaoki 
1. @neynt 
1. @chang-zhao 
1. @danielquinn 
1. @fdg-org 
1. @smileboywtu 
1. @thorsummoner 
1. @tomazcunha 
1. @sebuls 
1. @Soulou 
1. @timgates42 
1. @SunyataZero 
1. @vaurelios 
1. @wolfv 
1. @dharmatech 
1. @hadware 
1. @nazgul77 
1. @Xoristzatziki

**Comment by neynt** [comment]
Granted

**Comment by anarcat** [comment]
On 2024-05-12 17:59:45, Dan Yeaw wrote:
> ## No Response Yet
>
> 1. @anarcat 

I :+1: the comment where i was pinged, hoping to reduce the maddening
amount of noise everyone is receiving here, sorry if that was missed.

Agreed.

**Comment by wolfv** [comment]
You got my permission.

**Comment by sebuls** [comment]
I agree.
Thank you.

2024년 5월 13일 (월) 09:59, Dan Yeaw ***@***.***>님이 작성:

**Comment by osamuaoki** [comment]
I agree.  Thank you.

**Comment by danyeaw** [comment]
One last push, I pulled emails from Git and GitHub for 12 of the remaining contributors and emailed them asking for their permission.

**Comment by danyeaw** [comment]
Hi @sebp, we have more than a 3/4 supermajority who have responded yes with no concerns or objections. I also attempted to email everyone who hasn't responded, where I got a couple of additional yes responses. Everyone who didn't respond made minor contributions (much appreciated contributions!).

Since GFDL and LPGL are both copyleft licenses, I don't think there would be any objections or impact by changing the license to make it more compatible with PyGObject.

Since this project is a collective work, I think you as the main author have the ability to upgrade the license. I think we did our due diligence to make sure there were no objections from the community. Thanks everyone for all the responses!

**Comment by osamuaoki** [comment]
Here is another data point.

I made a quick and rough analysis with "git blame" over 27081 lines in HEAD.

* 97.16% of lines are committed only with 15 names/email.
* 98.98% of lines are committed only with 23 names/email.

```
lines       name    email
----------------------------------------------------
9469	Sebastian Pölsterl	<sebp_at_k-d-w.org>
4831	Anders Jonsson	<anders.jonsson_at_norsjovallen.se>
3952	Rafael Fontenelle	<rffontenelle_at_users.noreply.github.com>
3482	edd1fd86 translations/po/de_DE.po	translations/po/de_DE.po
1910	Christoph Reiter	<reiter.christoph_at_gmail.com>
532	^a0858ac (Sebastian	^a0858ac
468	Calum Lind	<calumlind_at_gmail.com>
337	Gian Mario	<tingping_at_tingping.se>
299	Lucas Baudin	<gianmt_at_gnome.org>
234	TingPing	<rafaelff_at_gnome.org>
204	Patrick Griffis	<xapantu_at_gmail.com>
194	Carsten Csiky	<carsten.csiky_at_gmail.com>
138	Andrew Higginson	<at.higginson_at_gmail.com>
134	Chris Mayo	<aklhfex_at_gmail.com>
123	Cyril Danilevski	<cydanil_at_gmail.com>
94	Hadrien Titeux	<hadwarez_at_gmail.com>
91	Ηλιάδης Ηλίας	<Xoristzatziki_at_users.noreply.github.com>
78	Wolf Vollprecht	<w.vollprecht_at_gmail.com>
63	Jim Zhang	<thorsummoner_at_live.com>
48	vaporup	<Hyriodula_at_gmail.com>
47	Luis Menina	<fana_at_2flub.org>
39	thorsummoner	<liberforce_at_freeside.fr>
38	Osamu Aoki	<osamu_at_debian.org>
....
```
@sebp seems to be recorded in several ways.

If you count "majority" by the lines, I think we may be able to say well over 95% super majority has been reached.

Osamu

Script used for above result (with LibreOffice and nvim):
```
#!/bin/bash
# Copyright (c) 2024 Osamu Aoki <osamu@debian.org>
# GNU GPL 2+
for f in $(find . -path ./.git -prune -o -type f -print); do git blame -w $f; done >blame_name.base
wc -l blame_name.base
sed -e "s/^[0-9a-f][0-9a-f]* *(//" blame_name.base | cut -d ' ' -f 1,2 >blame_name.list
sort blame_name.list |uniq -c | sort -n -r >blame_name.sort
for f in $(find . -path ./.git -prune -o -type f -print); do git blame -w -e $f; done > blame_email.base
wc -l blame_email.base
sed -e "s/^[0-9a-f][0-9a-f]* //" blame_email.base | cut -d ' ' -f 1 >blame_email.list
sort blame_email.list |uniq -c |sort -n -r >blame_email.sort
git log | grep "^Author:" | sed "s/^Author: *//" > commit_author.list
wc -l commit_author.list
sort commit_author.list |uniq -c |sort -n -r >commit_author.sort
```

**Comment by sebp** [comment]
@danyeaw Thanks a lot for your work on reaching out to everyone that contributed. I think it is reasonable to apply the change of license based on current responses. I'd appreciate if you could provide a final list of people that did not respond, just to have this documented.

**Comment by danyeaw** [comment]
Hi @sebp, the final list of contributors who didn't respond is: @hadware, @Xoristzatziki, @hcpl, @rpunkfu, @and471, @xapantu, @chang-zhao, @fdg-org,  @smileboywtu, @thorsummoner, @tomazcunha, @Soulou, @timgates42, @SunyataZero, @vaurelios, @dharmatech, and @nazgul77. Thanks!

**Comment by hadware** [comment]
Sorry, I thought I answered, but it was on another issue. I agree with the re-licensing.

**Comment by tomazcunha** [comment]
Yes. :)
