### ISSUE TITLE
Update versions in environment.yml

### ISSUE THREAD

**Issue by rffontenelle** [sebp/PyGObject-Tutorial#226]
Considering the versions update in requitements.txt and in Dockerfile, I assume we need to have environments.yml updated as well to keep rtd up with some versions. (I'd do myself but I'm not familiar with the version constraints in there)

P.s. consider enabling RTD preview for pull requests, see https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by sebp** [comment]
Good catch, thanks for letting me know!
