### ISSUE TITLE
GtkAction is deprecated in favour of GAction

### ISSUE THREAD

**Issue by stuaxo** [sebp/PyGObject-Tutorial#42]
According to 
https://developer.gnome.org/gtk3/stable/GtkAction.html

Warning
gtk_action_new has been deprecated since version 3.10 and should not be used in newly-written code. Use GAction instead, associating it to a widget with GtkActionable or creating a GtkMenu with gtk_menu_new_from_model()

The tutorial still recommends GtkAction.

**Comment by sebp** [comment]
Fixed with PR #73.
