### ISSUE TITLE
Give example of using a Gtk Stock Item (e.g. for a button)

### ISSUE THREAD

**Issue by muelli** [sebp/PyGObject-Tutorial#47]
I'm intending to use a Stock Item for a button. I found the tutorial by googling for "Gtk use stock item" and while I appreciate seeing the various icons, I'd love to see an example of how to actually use such a stock item, e.g. with a button.

I finally found the following to work:

```
        image = Gtk.Image()
        image.set_from_stock(Gtk.STOCK_ABOUT, Gtk.IconSize.BUTTON)
        self.button = Gtk.Button(
            #label='Hello',
            #stock=Gtk.STOCK_ABOUT,
            image=image,
            )
```

Another option might be to ignore the default settings (per http://stackoverflow.com/a/3175809/2015768):
```
        settings = Gtk.Settings.get_default()
        settings.props.gtk_button_images = True

        self.button = Gtk.Button(
            #label='Hello',
            stock=Gtk.STOCK_ABOUT,
            #image=image,
            )

```

**Comment by oaubert** [comment]
Stock items have been deprecated in Gtk3.10 (and this triggers warnings in many apps). See https://docs.google.com/document/d/1KCVPoYQBqMbDP11tHPpjW6uaEHrvLUmcDPqKAppCY8o/pub for some rationale (with which I do not agree - replacing a set of generic constants by strings you have to look up in some table seems rather retrograde to me)

**Comment by sebp** [comment]
The use of stock icons was removed in commit f0add93123b87b9cc5ad079a65ae19fe41e937fa.

**Comment by rubyFeedback** [comment]
It should be noted that "stock items" are available, if the icon theme at hand supports it. 

For example, adwaita icon theme on my system has 923 stock images available right now.
They don't quite look like the old gtk2 stock items, but they are still nice and perfectly
usable.
