### ISSUE TITLE
FileChooserDialog doesn't group the directories together?

### ISSUE THREAD

**Issue by sdouble** [sebp/PyGObject-Tutorial#61]
Is this something new with pygobject or gtk3?  I'm using Python 3.4.2 with Gtk 3.0 and my directories aren't grouped the way they usually are.

![image](https://cloud.githubusercontent.com/assets/2735777/5927431/fa3e7ccc-a637-11e4-8e93-f73a570b5544.png)

**Comment by gianmt** [comment]
pygobject does not do anything special with the filechooser, it's just a wrapper on top of the C API, I believe it's a change made in GTK+3 itself.

**Comment by sdouble** [comment]
Thanks for the reply gianmt.  There is a demo binary that came with GTK+3 (gtk3-demo.exe in my case) that shows the FileChooser with directories grouped.  Since the demo was written in C, I assumed either PyGObject was causing the issue or there is something missing from this tutorial to cause this behavior.

**Comment by spiessbuerger** [comment]
Isn't this just the normal behaviour of GTK3? The file choosers in a lot of programs run on Gnome 3 sort the files and folders this way.

**Comment by sebp** [comment]
You can change this in Nautilus' settings. Anyway, this is completed unrelated to pygobject and this tutorial.

**Comment by sdouble** [comment]
Thank you sepb.  I'm running this on Windows so was unaware of a Nautilus setting.  I mentioned earlier that the demo application (written in C) that came with gtk3 is grouping the directories but this did not, so I wasn't sure if it was something done differently in this tutorial.  My apologies for the misunderstanding.
