### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by tobias47n9e** [sebp/PyGObject-Tutorial#65]
A chapter about packaging would be really useful in my opinion. I am currently trying to find out how this is done and most tutorials focus on command-line tools that are distributed over the PyPI. It would be nice if there were a tutorial that shows how to make a deb or rpm that integrates into a distribution (a icon in the dash; starting the program by entering the name into the terminal).

**Comment by sebp** [comment]
It is not supposed to cover all aspects of Python development, it is only on how to use Gtk+ and associated libraries. Please refer to distribution's packaging guidelines for further details.
