### ISSUE TITLE
UIManager deprecated

### ISSUE THREAD

**Issue by tobias47n9e** [sebp/PyGObject-Tutorial#68]
Chapter 16 about menus uses the UIManger which is deprecated since GTK 3.10. I was looking at how to update the example, but I haven't come up with a solution yet.

 - https://github.com/sebp/PyGObject-Tutorial/blob/master/source/menus.txt

**Comment by sebp** [comment]
This was partially addressed by PR #73, but I would like to see a more detailed example of using Gtk.Application and friends.

**Comment by TingPing** [comment]
@sebp Such as?

**Comment by sebp** [comment]
The example should demonstrate how to use toggle and radio actions and grouping elements into sections, https://wiki.gnome.org/HowDoI/ApplicationMenu would be a good start.
