### ISSUE TITLE
Installation: build gtk+-3 with jhbuild

### ISSUE THREAD

**Issue by pksadiq** [sebp/PyGObject-Tutorial#87]
gtk+ has now branched and building gtk+ using jhbuild might build gtk+ master branch (which is gtk4).

So explicitly say to build gtk+-3: jhbuild build gtk+-3

Thanks.

**Comment by sebp** [comment]
Yes, gtk+ master corresponds to 
AFAICT, there is no gtk+-3 target in jhbuild
