### ISSUE TITLE
Gtk.Stack does allow setting the visible child

### ISSUE THREAD

**Issue by danjjl** [sebp/PyGObject-Tutorial#88]
In `layout.txt` it is written:

> `Gtk.Stack` does not provide a means for users to change the visible child.

However, as of version 3.10, `Gtk.Stack` allows setting the visible child using: `set_visible_child(child)`.

**Comment by sebp** [comment]
This part is taken from the [official GTK+ 3 reference manual](https://developer.gnome.org/gtk3/stable/GtkStack.html). You should file a bug at https://bugzilla.gnome.org instead.
