### ISSUE TITLE
Gtk.Builder example typo

### ISSUE THREAD

**Issue by hcpl** [sebp/PyGObject-Tutorial#90]
The code included as the last example in [section 19.3 "Connecting Signals"](http://python-gtk-3-tutorial.readthedocs.io/en/latest/builder.html#connecting-signals) is:
```rst
.. literalinclude:: ../examples/builder_example.py
    :linenos:
    :lines: 3-12
```
```python
from gi.repository import Gtk

class Handler:
    def onDeleteWindow(self, *args):
        Gtk.main_quit(*args)

    def onButtonPressed(self, button):
        print("Hello World!")

builder = Gtk.Builder()
```
The last line should be
```python
builder.connect_signals(Handler())
```
which is [line 14](https://github.com/sebp/PyGObject-Tutorial/blob/master/examples/builder_example.py#L14) of builder_example.py.

**Comment by sebp** [comment]
Thanks for reporting! Could you create a pull request please?

**Comment by hcpl** [comment]
Done: #91.
